language: scala

script:
  - "mvn clean test"

scala:
  - 2.11.1

jdk:
  - oraclejdk7

services:
  - redis

env:
  - MAVEN_OPTS="-ea -server -Xmx8192m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
