language: scala

script:
  - "sbt ++$TRAVIS_SCALA_VERSION test"
after_script:
  - "sbt coveralls"

scala:
  - 2.10.4

jdk:
  - oraclejdk7

services:
  - redis

env:
  - SBT_OPTS="-ea -server -Xmx8192m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
